# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-ID: 'UA-112060364-2' 暂时注释谷歌统计

menu:
- {name: '文章',  url: 'facts'}  #原先是interesting facts,改为文章
- #{name: 'Learning Resources', url: 'resources'}  #暂时注释
- #{name: 'Sample Posts',       url: 'sample-posts'} #暂时注释
- #{name: 'Documentation',      url: 'documentation'}  #暂时注释
- {name: '关于我',              url: 'about'}  #原先是about,改为关于我
- #{name: 'Contact',            url: 'contact'}  #暂时注释

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://v.douyin.com/DVXqSJq/'} #原先是twitter,改为抖音主页
- #{icon: 'facebook', link:   'https://www.facebook.com/paululele'}  #原先是facebook,暂时注释
- #{icon: 'instagram', link:  'https://instagram.com/paululele'} #原先是instagram,暂时注释
- #{icon: 'envelope', link:   'mailto:hello@paulle.ca'}  #原先是evelope,暂时注释
- #{icon: 'rss-square', link: 'feed.xml'}  #原先是rss-square,暂时注释
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
